[package]
name = "furnace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rrplug =  { path = "../rrplug" }
dotenv = "0.15.0"
base64 = "0.21.0"
once_cell = "1.16.0"
egui-winit = "0.20.1"
eframe = { git = "https://github.com/catornot/egui.git", default-features = false, features = ["wgpu","default_fonts"] }


[build-dependencies]
windres = "0.2.2"

[lib]
crate-type = ["cdylib"]