[package]
name = "furnace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rrplug =  { path = "../rrplug" }
dotenv = "0.15.0"

[build-dependencies]
windres = "0.2.2"

[lib]
crate-type = ["cdylib"]